version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
    volumes:
      - ./backend:/app
      - ./firebase-credentials.json:/app/firebase-credentials.json
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ai-chatbot-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_FIREBASE_API_KEY=AIzaSyBSHzi0qb2iwTzB-KDIE_XRKII3APkZhCg
      - REACT_APP_FIREBASE_AUTH_DOMAIN=clron-2.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=clron-2
      - REACT_APP_FIREBASE_STORAGE_BUCKET=clron-2.firebasestorage.app
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=661074106893
      - REACT_APP_FIREBASE_APP_ID=1:661074106893:web:51060f9522c50b39695344
    depends_on:
      - backend
    restart: unless-stopped