version: '3.8'

services:
  ai-chatbot-dev:
    build: .
    container_name: ai-chatbot-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev