# .github/workflows/backend-deploy.yml
# Updated to use environment variables safely
name: Deploy Backend to Cloud Run
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Use credentials_json properly
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - uses: google-github-actions/setup-gcloud@v1
      
      # Create firebase-credentials.json from secret
      - name: Create Firebase credentials file
        run: |
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > firebase-credentials.json
      
      # Build and push container
      - name: Build and push container
        run: |
          cd backend
          cp ../firebase-credentials.json .
          gcloud builds submit --tag gcr.io/clron-2/clron-backend
          
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy clron-backend \
            --image gcr.io/clron-2/clron-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }},FIREBASE_STORAGE_BUCKET=clron-2.appspot.com,FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json"